AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for the backend

Parameters:
  GithubRepoName:
    Type: String
    Description: Name of the GitHub repo where the project is stored.

  ServiceName:
    Type: String
    Description: Name of service. Prepends domain name
    Default: medsum

Resources:
  ##### STATIC HOSTING #####
  # Bucket to host static web assets
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  # Identity to allow cloudFront to access our private bucket.
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Default Origin Access Control
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket policy that allows the aboe OAI to access the bucket.
  HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostingBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub ${HostingBucket.Arn}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}

  # CDN to front and cache the website
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${ServiceName}.demo.enpalm.se"
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: Assets
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: summaries/*
            CachePolicyId: !Ref SumariesCachePolicy
        DefaultCacheBehavior:
          AllowedMethods: # Which methods to forward to S3
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: # Which methods to cache responses for at cloudfront
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 60 # in seconds
          MaxTTL: 240 # in seconds
          MinTTL: 60 # in seconds
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: S3Origin
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt HostingBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
          - Id: Assets
            DomainName: !GetAtt SummariesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        IPV6Enabled: false
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:675385716628:certificate/73557123-bfc3-4e9c-84b3-afcf1df5b00e
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
      Tags:
        - Key: project
          Value: !Ref ServiceName

  SumariesCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 60
        MaxTTL: 60
        MinTTL: 60
        Name: SumariesCachePolicy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: False
          EnableAcceptEncodingGzip: True
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # Parameter used by frontend deployment pipeline
  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Hosting bucket name"
      Name: !Sub "${GithubRepoName}-hosting-bucket"
      Type: String # Required
      Value: !Ref HostingBucket # Required

  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: demo.enpalm.se.
      RecordSets:
        - Name: !Sub "${ServiceName}.demo.enpalm.se."
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudfrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  ##### Process data #####
  # Bucket to upload data to
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "upload-${AWS::AccountId}-${AWS::Region}" # Explicit name only to avoid circular dependency on Lambda
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: ExpireRule
            Status: Enabled
            ExpirationInDays: 2 # Automatically delete object after 2 days
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
            Id: MyCORSRuleId1
            MaxAge: 3600
      Tags:
        - Key: project
          Value: !Ref ServiceName

  # Bucket to store summaries in
  SummariesBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: ExpireRule
            Status: Enabled
            ExpirationInDays: 2 # Automatically delete object after 2 days
      Tags:
        - Key: project
          Value: !Ref ServiceName

  # Gen presigned URL
  GenPresignedUrlLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/gen_presign/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          INGEST_BUCKET: !Ref UploadBucket
      Policies:
        - Statement:
            - Sid: GenPresignedPermissionPolicy
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${UploadBucket}/*"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - !Sub "https://${ServiceName}.demo.enpalm.se"

  # Summarise function.
  SummarizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_summary
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 2048
      Timeout: 45
      Tags:
        project: !Ref ServiceName
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "upload-${AWS::AccountId}-${AWS::Region}" # Explicit name only to avoid circular dependency on Lambda
        - S3CrudPolicy:
            BucketName: !Ref SummariesBucket
      Environment:
        Variables:
          DESTINATION_BUCKETNAME: !Ref SummariesBucket
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:
  DomainUrlCloudfront:
    Value: !GetAtt CloudfrontDistribution.DomainName
    Description: Cloudfront distribution URL.

  BucketNameParameter:
    Value: !Ref BucketNameParameter
    Description: Name of the SSM paramter containing the S3 hosting bucket name.
