AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for the backend

Parameters:
  GithubRepoName:
    Type: String
    Description: Name of the GitHub repo where the project is stored.

  ServiceName:
    Type: String
    Description: Name of service. Prepends domain name
    Default: medsum

Resources:
  ### STATIC HOSTING

  # Bucket to host static web assets
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  # Identity to allow cloudFront to access our private bucket.
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Default Origin Access Control
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket policy that allows the aboe OAI to access the bucket.
  HostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostingBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub ${HostingBucket.Arn}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}

  # CDN to front and cache the website
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${ServiceName}.demo.enpalm.se"
        DefaultCacheBehavior:
          AllowedMethods: # Which methods to forward to S3
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: # Which methods to cache responses for at cloudfront
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 60 # in seconds
          MaxTTL: 240 # in seconds
          MinTTL: 60 # in seconds
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: S3Origin
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt HostingBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        IPV6Enabled: false
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:675385716628:certificate/73557123-bfc3-4e9c-84b3-afcf1df5b00e
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Hosting bucket name"
      Name: !Sub "${GithubRepoName}-hosting-bucket"
      Type: String # Required
      Value: !Ref HostingBucket # Required

  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: demo.enpalm.se.
      RecordSets:
        - Name: !Sub "${ServiceName}.demo.enpalm.se."
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudfrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  ### Upload data

Outputs:
  DomainUrlCloudfront:
    Value: !GetAtt CloudfrontDistribution.DomainName
    Description: Cloudfront distribution URL.

  BucketNameParameter:
    Value: !Ref BucketNameParameter
    Description: Name of the SSM paramter containing the S3 hosting bucket name.
